// Public klasöründeki görseller (sıralı)
const publicImages = [
  "/1.jpg",
  "/2.jpg",
  "/3.png",
  "/4.jpg",
  "/5.jpg",
  "/6.jpg",
  "/7.jpg",
  "/8.jpg",
  "/9.jpg",
  "/10.jpg",
  "/11.jpg",
  "/12.jpg",
  "/13.jpg",
  "/14.jpg",
  "/15.jpg",
  "/16.jpg",
  "/17.jpg",
  "/18.jpg",
  "/19.jpg",
  "/20.jpg",
];

// Helper function to get image from public folder (sıralı)
function getPublicImage(index: number): string {
  return publicImages[index % publicImages.length];
}

export type Product = {
  id: string;
  title: string;
  brand: string;
  category: "Automation Systems" | "Motor & Motion" | "Energy & Power";
  subCategory: string;
  series?: string;
  specs: {
    [key: string]: string;
  };
  condition:
    | "Sıfır (Kapalı Kutu)"
    | "Sıfır (Açık Kutu)"
    | "Yeni Gibi"
    | "Yenilenmiş"
    | "İkinci El (Temiz)"
    | "Yedek Parça / Arızalı";
  price: number;
  currency: "USD" | "TRY";
  stock: number;
  imageUrl: string;
  sellerName: string; // Bu asla gösterilmeyecek!
  partNumber?: string;
};

// Ürünler array'i - imageUrl'ler otomatik olarak sıralı index ile atanacak
const productsData: Omit<Product, "imageUrl">[] = [
  // Automation Systems - PLC
  {
    id: "1",
    title: "Siemens Simatic S7-1200 PLC",
    brand: "Siemens",
    category: "Automation Systems",
    subCategory: "PLC CPU",
    series: "S7-1200",
    specs: {
      inputs: "14 DI",
      outputs: "10 DO",
      communication: "Profinet",
    },
    condition: "Sıfır (Kapalı Kutu)",
    price: 1250,
    currency: "USD",
    stock: 3,
    sellerName: "TechCorp Industrial Solutions",
    partNumber: "6ES7214-1AG40-0XB0",
  },
  {
    id: "9",
    title: "Schneider Electric Modicon M221 PLC",
    brand: "Schneider Electric",
    category: "Automation Systems",
    subCategory: "PLC CPU",
    series: "Modicon M221",
    specs: {
      inputs: "14 DI",
      outputs: "10 DO",
      communication: "Modbus TCP",
    },
    condition: "Sıfır (Açık Kutu)",
    price: 380,
    currency: "USD",
    stock: 8,
    sellerName: "Control Systems International",
    partNumber: "TM221CE24R",
  },
  {
    id: "13",
    title: "Allen-Bradley CompactLogix L16ER PLC",
    brand: "Allen-Bradley",
    category: "Automation Systems",
    subCategory: "PLC CPU",
    series: "CompactLogix",
    specs: {
      inputs: "32 DI",
      outputs: "32 DO",
      communication: "EtherNet/IP",
    },
    condition: "Yedek Parça / Arızalı",
    price: 950,
    currency: "USD",
    stock: 1,
    sellerName: "Rockwell Solutions Group",
    partNumber: "1769-L16ER-BB1B",
  },
  {
    id: "16",
    title: "Omron CP1E-N30DR-A PLC",
    brand: "Omron",
    category: "Automation Systems",
    subCategory: "PLC CPU",
    series: "CP1E",
    specs: {
      inputs: "18 DI",
      outputs: "12 DO",
      communication: "RS-232",
    },
    condition: "Yeni Gibi",
    price: 320,
    currency: "USD",
    stock: 7,
    sellerName: "PLC Solutions Worldwide",
    partNumber: "CP1E-N30DR-A",
  },
  {
    id: "21",
    title: "Siemens Simatic ET 200SP Distributed I/O",
    brand: "Siemens",
    category: "Automation Systems",
    subCategory: "PLC CPU",
    series: "ET 200SP",
    specs: {
      inputs: "16 DI",
      outputs: "16 DO",
      communication: "Profinet",
    },
    condition: "Sıfır (Kapalı Kutu)",
    price: 1150,
    currency: "USD",
    stock: 4,
    sellerName: "Distributed Systems Corp.",
    partNumber: "6ES7134-6DB00-0BA1",
  },
  {
    id: "24",
    title: "Allen-Bradley ControlLogix L75 PLC",
    brand: "Allen-Bradley",
    category: "Automation Systems",
    subCategory: "PLC CPU",
    series: "ControlLogix",
    specs: {
      inputs: "32 DI",
      outputs: "32 DO",
      communication: "EtherNet/IP",
    },
    condition: "Yeni Gibi",
    price: 2450,
    currency: "USD",
    stock: 1,
    sellerName: "Advanced Control Systems",
    partNumber: "1756-L75",
  },
  {
    id: "28",
    title: "Omron NX1P2-9024 Programmable Controller",
    brand: "Omron",
    category: "Automation Systems",
    subCategory: "PLC CPU",
    series: "NX1P",
    specs: {
      inputs: "16 DI",
      outputs: "16 DO",
      communication: "EtherCAT",
    },
    condition: "Yenilenmiş",
    price: 680,
    currency: "USD",
    stock: 5,
    sellerName: "Programmable Control Experts",
    partNumber: "NX1P2-9024DT",
  },
  // Automation Systems - HMI
  {
    id: "5",
    title: "Allen-Bradley PanelView Plus 7 HMI",
    brand: "Allen-Bradley",
    category: "Automation Systems",
    subCategory: "HMI",
    series: "PanelView Plus",
    specs: {
      screen: "7 inch",
      resolution: "800x480",
      communication: "EtherNet/IP",
    },
    condition: "Sıfır (Kapalı Kutu)",
    price: 2100,
    currency: "USD",
    stock: 1,
    sellerName: "Rockwell Automation Partners",
    partNumber: "2711P-T10C4D8",
  },
  {
    id: "10",
    title: "Siemens Simatic HMI KTP700 Basic",
    brand: "Siemens",
    category: "Automation Systems",
    subCategory: "HMI",
    series: "KTP700",
    specs: {
      screen: "7 inch",
      resolution: "800x480",
      communication: "Profinet",
    },
    condition: "Yeni Gibi",
    price: 550,
    currency: "USD",
    stock: 2,
    sellerName: "HMI Solutions Corp.",
    partNumber: "6AV2123-2GA03-0AX0",
  },
  {
    id: "20",
    title: "Schneider Electric Magelis HMI",
    brand: "Schneider Electric",
    category: "Automation Systems",
    subCategory: "HMI",
    series: "Magelis",
    specs: {
      screen: "5.7 inch",
      resolution: "320x240",
      communication: "Modbus TCP",
    },
    condition: "Sıfır (Açık Kutu)",
    price: 650,
    currency: "USD",
    stock: 5,
    sellerName: "HMI Display Solutions",
    partNumber: "XBTGT5330",
  },
  {
    id: "30",
    title: "Allen-Bradley Studio 5000 View Designer HMI",
    brand: "Allen-Bradley",
    category: "Automation Systems",
    subCategory: "HMI",
    series: "PanelView",
    specs: {
      screen: "10 inch",
      resolution: "1024x600",
      communication: "EtherNet/IP",
    },
    condition: "Yenilenmiş",
    price: 1890,
    currency: "USD",
    stock: 2,
    sellerName: "HMI Design Solutions",
    partNumber: "2711P-K10C8D8",
  },
  // Motor & Motion - Servo Motors
  {
    id: "3",
    title: "Omron 750W AC Servo Motor",
    brand: "Omron",
    category: "Motor & Motion",
    subCategory: "Servo Motors",
    series: "G5 Series",
    specs: {
      power: "0.75kW",
      voltage: "220V",
      rpm: "3000 RPM",
    },
    condition: "Sıfır (Açık Kutu)",
    price: 890,
    currency: "USD",
    stock: 5,
    sellerName: "Motion Control Systems",
    partNumber: "R88M-G20030H-S2",
  },
  {
    id: "17",
    title: "ABB M2BA Three-Phase Motor",
    brand: "ABB",
    category: "Motor & Motion",
    subCategory: "Servo Motors",
    series: "M2BA",
    specs: {
      power: "1.5kW",
      voltage: "380V",
      rpm: "3000 RPM",
    },
    condition: "İkinci El (Temiz)",
    price: 580,
    currency: "USD",
    stock: 3,
    sellerName: "Motor Warehouse Inc.",
    partNumber: "M2BA 132 SMB 4",
  },
  {
    id: "25",
    title: "Siemens SIMOCODE Pro Motor Management",
    brand: "Siemens",
    category: "Motor & Motion",
    subCategory: "Servo Motors",
    series: "SIMOCODE",
    specs: {
      power: "0.4kW",
      voltage: "220V",
      rpm: "1500 RPM",
    },
    condition: "Yeni Gibi",
    price: 380,
    currency: "USD",
    stock: 8,
    sellerName: "Motor Management Systems",
    partNumber: "3UF7010-1AA00-0",
  },
  // Energy & Power - VFD
  {
    id: "6",
    title: "Siemens Sinamics G120 Variable Frequency Drive",
    brand: "Siemens",
    category: "Energy & Power",
    subCategory: "AC Drives (VFD)",
    series: "Sinamics G120",
    specs: {
      power: "1.5kW",
      voltage: "380V",
      frequency: "0-650 Hz",
    },
    condition: "Yenilenmiş",
    price: 650,
    currency: "USD",
    stock: 4,
    sellerName: "Drive Solutions Ltd.",
    partNumber: "6SL3210-1KE23-2AF1",
  },
  {
    id: "8",
    title: "ABB ACS550 Variable Frequency Drive",
    brand: "ABB",
    category: "Energy & Power",
    subCategory: "AC Drives (VFD)",
    series: "ACS550",
    specs: {
      power: "2.2kW",
      voltage: "380V",
      frequency: "0-500 Hz",
    },
    condition: "Yeni Gibi",
    price: 720,
    currency: "USD",
    stock: 3,
    sellerName: "Industrial Automation Group",
    partNumber: "ACS550-01-025A-4",
  },
  {
    id: "12",
    title: "ABB ACS580 Variable Frequency Drive",
    brand: "ABB",
    category: "Energy & Power",
    subCategory: "AC Drives (VFD)",
    series: "ACS580",
    specs: {
      power: "5.5kW",
      voltage: "380V",
      frequency: "0-500 Hz",
    },
    condition: "Sıfır (Açık Kutu)",
    price: 1850,
    currency: "USD",
    stock: 2,
    sellerName: "Drive Technologies Inc.",
    partNumber: "ACS580-01-025A-4",
  },
  {
    id: "15",
    title: "Schneider Electric Altivar ATV320 Drive",
    brand: "Schneider Electric",
    category: "Energy & Power",
    subCategory: "AC Drives (VFD)",
    series: "Altivar ATV320",
    specs: {
      power: "0.75kW",
      voltage: "220V",
      frequency: "0-400 Hz",
    },
    condition: "Yedek Parça / Arızalı",
    price: 420,
    currency: "USD",
    stock: 6,
    sellerName: "Variable Speed Solutions",
    partNumber: "ATV320U07M2C",
  },
  {
    id: "19",
    title: "Allen-Bradley PowerFlex 525 VFD",
    brand: "Allen-Bradley",
    category: "Energy & Power",
    subCategory: "AC Drives (VFD)",
    series: "PowerFlex 525",
    specs: {
      power: "3.7kW",
      voltage: "380V",
      frequency: "0-590 Hz",
    },
    condition: "Yeni Gibi",
    price: 780,
    currency: "USD",
    stock: 2,
    sellerName: "Rockwell Automation Direct",
    partNumber: "25B-D2P3N104",
  },
  {
    id: "23",
    title: "Omron MX2 Variable Frequency Drive",
    brand: "Omron",
    category: "Energy & Power",
    subCategory: "AC Drives (VFD)",
    series: "MX2",
    specs: {
      power: "1.1kW",
      voltage: "220V",
      frequency: "0-400 Hz",
    },
    condition: "Yenilenmiş",
    price: 540,
    currency: "USD",
    stock: 6,
    sellerName: "Frequency Control Solutions",
    partNumber: "MX2-2S2004",
  },
  // Automation Systems - Sensors
  {
    id: "7",
    title: "Omron E3X-DA11-S Fiber Optic Sensor",
    brand: "Omron",
    category: "Automation Systems",
    subCategory: "Sensors",
    series: "E3X",
    specs: {
      type: "Fiber Optic",
      detection: "0.05mm",
      response: "0.1ms",
    },
    condition: "Sıfır (Açık Kutu)",
    price: 125,
    currency: "USD",
    stock: 15,
    sellerName: "Sensor Technologies Co.",
    partNumber: "E3X-DA11-S",
  },
  {
    id: "11",
    title: "Omron E5CC Digital Temperature Controller",
    brand: "Omron",
    category: "Automation Systems",
    subCategory: "Sensors",
    series: "E5CC",
    specs: {
      type: "Temperature",
      range: "-50 to 400°C",
      accuracy: "±0.3%",
    },
    condition: "Yenilenmiş",
    price: 195,
    currency: "USD",
    stock: 10,
    sellerName: "Temperature Control Systems",
    partNumber: "E5CC-RX2ASM-800",
  },
  {
    id: "26",
    title: "Schneider Electric Harmony XB4 Push Button",
    brand: "Schneider Electric",
    category: "Automation Systems",
    subCategory: "Sensors",
    series: "Harmony XB4",
    specs: {
      type: "Push Button",
      voltage: "24V DC",
      contact: "1NO",
    },
    condition: "Yedek Parça / Arızalı",
    price: 25,
    currency: "USD",
    stock: 50,
    sellerName: "Control Components Warehouse",
    partNumber: "XB4BA31",
  },
  // Energy & Power - Circuit Breakers
  {
    id: "2",
    title: "Schneider Electric TeSys Contactor",
    brand: "Schneider Electric",
    category: "Energy & Power",
    subCategory: "Circuit Breakers",
    series: "TeSys",
    specs: {
      current: "9A",
      voltage: "380V AC",
      poles: "3",
    },
    condition: "Yeni Gibi",
    price: 85,
    currency: "USD",
    stock: 12,
    sellerName: "Automation Warehouse Inc.",
    partNumber: "LC1D09BD",
  },
  {
    id: "18",
    title: "Siemens 3RV2 Circuit Breaker",
    brand: "Siemens",
    category: "Energy & Power",
    subCategory: "Circuit Breakers",
    series: "3RV2",
    specs: {
      current: "0.16A",
      voltage: "690V AC",
      poles: "1",
    },
    condition: "Sıfır (Açık Kutu)",
    price: 145,
    currency: "USD",
    stock: 20,
    sellerName: "Electrical Components Co.",
    partNumber: "3RV2021-1AA10",
  },
  {
    id: "22",
    title: "ABB ACS880 Main Circuit Breaker",
    brand: "ABB",
    category: "Energy & Power",
    subCategory: "Circuit Breakers",
    series: "ACS880",
    specs: {
      current: "25A",
      voltage: "690V AC",
      poles: "3",
    },
    condition: "Yenilenmiş",
    price: 320,
    currency: "USD",
    stock: 3,
    sellerName: "Power Distribution Inc.",
    partNumber: "ACS880-01-025A-4",
  },
  {
    id: "29",
    title: "Siemens Sirius 3RM1 Motor Starter",
    brand: "Siemens",
    category: "Energy & Power",
    subCategory: "Circuit Breakers",
    series: "Sirius 3RM1",
    specs: {
      current: "7A",
      voltage: "690V AC",
      poles: "3",
    },
    condition: "Yedek Parça / Arızalı",
    price: 95,
    currency: "USD",
    stock: 15,
    sellerName: "Starter Components Co.",
    partNumber: "3RM1207-1AA04",
  },
  // Energy & Power - Safety Relays
  {
    id: "4",
    title: "ABB Soft Starter",
    brand: "ABB",
    category: "Energy & Power",
    subCategory: "Safety Relays",
    series: "PSS",
    specs: {
      power: "18kW",
      voltage: "380V",
      current: "35A",
    },
    condition: "Yeni Gibi",
    price: 450,
    currency: "USD",
    stock: 2,
    sellerName: "Power Systems Global",
    partNumber: "PSS 18/30-70",
  },
  {
    id: "14",
    title: "Siemens 3RW44 Soft Starter",
    brand: "Siemens",
    category: "Energy & Power",
    subCategory: "Safety Relays",
    series: "3RW44",
    specs: {
      power: "5.5kW",
      voltage: "380V",
      current: "12A",
    },
    condition: "Sıfır (Açık Kutu)",
    price: 680,
    currency: "USD",
    stock: 4,
    sellerName: "Motor Control Specialists",
    partNumber: "3RW4446-6BB44",
  },
  {
    id: "27",
    title: "ABB ACS800-07 Soft Starter Module",
    brand: "ABB",
    category: "Energy & Power",
    subCategory: "Safety Relays",
    series: "ACS800",
    specs: {
      power: "7.5kW",
      voltage: "380V",
      current: "15A",
    },
    condition: "Yenilenmiş",
    price: 750,
    currency: "USD",
    stock: 3,
    sellerName: "Starter Solutions Ltd.",
    partNumber: "ACS800-07-0200-3",
  },
];

// imageUrl'leri sıralı olarak atayarak final Product array'ini oluştur
export const mockProducts: Product[] = productsData.map((product, index) => ({
  ...product,
  imageUrl: getPublicImage(index),
}));
