export type Product = {
  id: string;
  title: string;
  brand: string;
  category: "PLC" | "Drive" | "HMI" | "Sensor" | "Motor" | "Contactor" | "Soft Starter" | "VFD";
  condition: "New in Box" | "Used";
  price: number;
  currency: "USD" | "TRY";
  stock: number;
  imageUrl: string;
  sellerName: string; // Bu asla gösterilmeyecek!
  partNumber?: string;
};

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Siemens Simatic S7-1200 PLC",
    brand: "Siemens",
    category: "PLC",
    condition: "New in Box",
    price: 1250,
    currency: "USD",
    stock: 3,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=Siemens+S7-1200",
    sellerName: "TechCorp Industrial Solutions",
    partNumber: "6ES7214-1AG40-0XB0",
  },
  {
    id: "2",
    title: "Schneider Electric TeSys Contactor",
    brand: "Schneider Electric",
    category: "Contactor",
    condition: "Used",
    price: 85,
    currency: "USD",
    stock: 12,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=TeSys+Contactor",
    sellerName: "Automation Warehouse Inc.",
    partNumber: "LC1D09BD",
  },
  {
    id: "3",
    title: "Omron AC Servo Motor",
    brand: "Omron",
    category: "Motor",
    condition: "New in Box",
    price: 890,
    currency: "USD",
    stock: 5,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=Omron+Servo",
    sellerName: "Motion Control Systems",
    partNumber: "R88M-G20030H-S2",
  },
  {
    id: "4",
    title: "ABB Soft Starter",
    brand: "ABB",
    category: "Soft Starter",
    condition: "Used",
    price: 450,
    currency: "USD",
    stock: 2,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=ABB+Soft+Starter",
    sellerName: "Power Systems Global",
    partNumber: "PSS 18/30-70",
  },
  {
    id: "5",
    title: "Allen-Bradley PanelView Plus 7 HMI",
    brand: "Allen-Bradley",
    category: "HMI",
    condition: "New in Box",
    price: 2100,
    currency: "USD",
    stock: 1,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=PanelView+Plus",
    sellerName: "Rockwell Automation Partners",
    partNumber: "2711P-T10C4D8",
  },
  {
    id: "6",
    title: "Siemens Sinamics G120 Variable Frequency Drive",
    brand: "Siemens",
    category: "VFD",
    condition: "Used",
    price: 650,
    currency: "USD",
    stock: 4,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=Sinamics+G120",
    sellerName: "Drive Solutions Ltd.",
    partNumber: "6SL3210-1KE23-2AF1",
  },
  {
    id: "7",
    title: "Omron E3X-DA11-S Fiber Optic Sensor",
    brand: "Omron",
    category: "Sensor",
    condition: "New in Box",
    price: 125,
    currency: "USD",
    stock: 15,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=Fiber+Optic+Sensor",
    sellerName: "Sensor Technologies Co.",
    partNumber: "E3X-DA11-S",
  },
  {
    id: "8",
    title: "ABB ACS550 Variable Frequency Drive",
    brand: "ABB",
    category: "VFD",
    condition: "Used",
    price: 720,
    currency: "USD",
    stock: 3,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=ACS550+VFD",
    sellerName: "Industrial Automation Group",
    partNumber: "ACS550-01-025A-4",
  },
  {
    id: "9",
    title: "Schneider Electric Modicon M221 PLC",
    brand: "Schneider Electric",
    category: "PLC",
    condition: "New in Box",
    price: 380,
    currency: "USD",
    stock: 8,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=Modicon+M221",
    sellerName: "Control Systems International",
    partNumber: "TM221CE24R",
  },
  {
    id: "10",
    title: "Siemens Simatic HMI KTP700 Basic",
    brand: "Siemens",
    category: "HMI",
    condition: "Used",
    price: 550,
    currency: "USD",
    stock: 2,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=KTP700+HMI",
    sellerName: "HMI Solutions Corp.",
    partNumber: "6AV2123-2GA03-0AX0",
  },
  {
    id: "11",
    title: "Omron E5CC Digital Temperature Controller",
    brand: "Omron",
    category: "Sensor",
    condition: "New in Box",
    price: 195,
    currency: "USD",
    stock: 10,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=E5CC+Controller",
    sellerName: "Temperature Control Systems",
    partNumber: "E5CC-RX2ASM-800",
  },
  {
    id: "12",
    title: "ABB ACS580 Variable Frequency Drive",
    brand: "ABB",
    category: "VFD",
    condition: "New in Box",
    price: 1850,
    currency: "USD",
    stock: 2,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=ACS580+VFD",
    sellerName: "Drive Technologies Inc.",
    partNumber: "ACS580-01-025A-4",
  },
  {
    id: "13",
    title: "Allen-Bradley CompactLogix L16ER PLC",
    brand: "Allen-Bradley",
    category: "PLC",
    condition: "Used",
    price: 950,
    currency: "USD",
    stock: 1,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=CompactLogix+L16",
    sellerName: "Rockwell Solutions Group",
    partNumber: "1769-L16ER-BB1B",
  },
  {
    id: "14",
    title: "Siemens 3RW44 Soft Starter",
    brand: "Siemens",
    category: "Soft Starter",
    condition: "New in Box",
    price: 680,
    currency: "USD",
    stock: 4,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=3RW44+Soft+Starter",
    sellerName: "Motor Control Specialists",
    partNumber: "3RW4446-6BB44",
  },
  {
    id: "15",
    title: "Schneider Electric Altivar ATV320 Drive",
    brand: "Schneider Electric",
    category: "VFD",
    condition: "Used",
    price: 420,
    currency: "USD",
    stock: 6,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=Altivar+ATV320",
    sellerName: "Variable Speed Solutions",
    partNumber: "ATV320U07M2C",
  },
  {
    id: "16",
    title: "Omron CP1E-N30DR-A PLC",
    brand: "Omron",
    category: "PLC",
    condition: "New in Box",
    price: 320,
    currency: "USD",
    stock: 7,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=CP1E+PLC",
    sellerName: "PLC Solutions Worldwide",
    partNumber: "CP1E-N30DR-A",
  },
  {
    id: "17",
    title: "ABB M2BA Three-Phase Motor",
    brand: "ABB",
    category: "Motor",
    condition: "Used",
    price: 580,
    currency: "USD",
    stock: 3,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=M2BA+Motor",
    sellerName: "Motor Warehouse Inc.",
    partNumber: "M2BA 132 SMB 4",
  },
  {
    id: "18",
    title: "Siemens 3RV2 Circuit Breaker",
    brand: "Siemens",
    category: "Contactor",
    condition: "New in Box",
    price: 145,
    currency: "USD",
    stock: 20,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=3RV2+Breaker",
    sellerName: "Electrical Components Co.",
    partNumber: "3RV2021-1AA10",
  },
  {
    id: "19",
    title: "Allen-Bradley PowerFlex 525 VFD",
    brand: "Allen-Bradley",
    category: "VFD",
    condition: "Used",
    price: 780,
    currency: "USD",
    stock: 2,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=PowerFlex+525",
    sellerName: "Rockwell Automation Direct",
    partNumber: "25B-D2P3N104",
  },
  {
    id: "20",
    title: "Schneider Electric Magelis HMI",
    brand: "Schneider Electric",
    category: "HMI",
    condition: "New in Box",
    price: 650,
    currency: "USD",
    stock: 5,
    imageUrl: "https://via.placeholder.com/400x300/1e293b/ffffff?text=Magelis+HMI",
    sellerName: "HMI Display Solutions",
    partNumber: "XBTGT5330",
  },
];

